### ISSUE TITLE
Remove arbitrary numbers in OpenApi JSON objects

### ISSUE THREAD

**Issue by AWinterman** [masseelch/elk#20]
Is it possible to remove the `359800019`from the Pet object here? 

https://github.com/masseelch/elk/blob/master/internal/openapi/ent/openapi.json#L1196

```
     "Pet359800019View": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "properties": {
          "age": {
            "type": "integer",
            "format": "int32",
            "example": 1
          },
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "example": "Kuro"
          }
        }
      }
    },
```

**Comment by AWinterman** [comment]
I looked into this for a bit but couldn't figure out how to fix it.

**Comment by AWinterman** [comment]
Ah I found it. view.Name uses a hash to ensure uniqueness... If this change is welcome I'm happy to make it.

**Comment by masseelch** [comment]
Hey @AWinterman. 

I already thought about this and have some ideas I want to share with you and get your opinion on. To provide some context:

I first developed the http-generator and afterwards the spec-generator. Reusing the "old" http-generator logic results in the hashed-names are present. This was initially meant to avoid responses with the exact same fields.

Since the OPAS is meant to be human readable to we indeed need to change the naming strategy. I have the following ideas in mind: 

1. Name the views according to their operation (`PetReadView`,`PetListView`,`PetCreateView`)
2. Just have the entity names
3. **Optional:** Let the user decide / override the naming strategy either globally or per node / operation

What do you think?

cc @a8m

**Comment by AWinterman** [comment]
looking at the objects, they seem mostly used in responses objects, and it's always the same object-- can it simply be `PetResponseView` in every case? Are there cases where they might collide?

I'm more in favor of a single option rather than many.

**Comment by masseelch** [comment]
When you start using serialization groups to include edges on a crud route they start to differ. 

If you don't, they all are the same. I'd like to keep the behavior of different views per operation but want to support your case as well. 

What about generating a single response object including every field and edge per default and enabling the current behaviour by passing in an option. The current behaviour will be changed to naming the responses after their operation instead of a hash (`PetReadView` etc) and the default behavior will simply be `Pet`.

**Comment by AWinterman** [comment]
I don't think I quite understand the problem still. Does one of the examples cover it? What should I look at to see what's being addressed with this functionality?

I do like using intelligible words more than the hash, in either case.

**Comment by masseelch** [comment]
The [simple](https://github.com/masseelch/elk/blob/165995bb7a6c95898e9955cd8caafe466dd9ef94/internal/simple/ent/openapi.json#L1471) example does. There are different `PetViews` since the properties of the responses are different from each other.

To play around with it, create schemas and make use of the serialization groups feature as explained in the [readme](https://github.com/masseelch/elk#serialization-groups).

However, eventually I want to decouple the spec generator from the handler-generator and then the serialization groups feature is more confusing then helping. I will create a PR this week and add you to review. I am confident we find a good solution to satisfy both our needs.

**Comment by AWinterman** [comment]
Okay, I'm updating the pets example (and I have to add support for openapi arrays as well) to generate a schema, locally, and I'm starting to understand the issue. Expect some updates to that illustrative pr while I better grock what the serialization groups are for and how they work.

**Comment by AWinterman** [comment]
I think my favorite option is to simply ask the user to name the view, and provide a response object per named view + the one default one that has all the fields. What do you think of that?

**Comment by masseelch** [comment]
I'll address this soon and add you as reviewer.

**Comment by AWinterman** [comment]
@masseelch heh, i didn't see this, but gave it a shot here https://github.com/masseelch/elk/pull/28
